package com.bepresent.android.ui.leaderboard

val possibleFakeUsernames = listOf(
    "Patible", "Effluvium", "Meconium", "Pizzazz", "Votation",
    "Clodhopper", "Iterant", "IllailDaedal", "PvpacidpUrial", "Pseudonym",
    "Querimonious", "LickoBonny", "Seneschal", "NobleisPodunk", "Cursorial",
    "CorieWasabi", "Dunnage", "Fungible", "GarrygarVeleta", "Indubitably",
    "Pedometer", "Bucolic", "Ephemeral", "Hullabaloo", "Subluxation",
    "Gossamer", "Wastelot", "RichfailKahuna", "Ancillary", "Flummery",
    "Encaustic", "Bugbear", "Thorax3Renal", "Dummkopf", "FuzzlighBerate",
    "RikulPaltry", "Inglenook", "Botryoidal", "Seicento", "GrandheavFeeble",
    "Wudzbird", "Absquatulate", "Krasisdhard8", "Gumshoe", "Adnascent",
    "Bogey", "Euphonon", "Fatuous", "Brayerjam77", "Grommet",
    "Brumous", "Bovicide", "Magnality", "Doppelganger", "Patriolatry",
    "Scofflaw", "Effulgent", "Euouae", "Nauseant", "Sprinkles",
    "Carniferous", "Furbelow", "Panache", "Zygote", "Formulaic",
    "Fancywork", "Interciliary", "Meatus", "Naturism", "Ecru",
    "Curiosa", "Kumquat", "Microlith", "Sashay", "Fucoidles1309",
    "Quizzity", "Deraymerz720", "Tomfoolery", "Juncaceous", "Waddle",
    "Michael Smith", "Emily Johnson", "Jacob Williams", "Olivia Brown",
    "Ethan Jones", "Ava Garcia", "William Rodriguez", "Sophia Martinez",
    "Matthew Miller", "Isabella Davis", "James Hernandez", "Mia Lopez",
    "Alexander Perez", "Charlotte Wilson", "Daniel Anderson", "Amelia Thomas",
    "Christopher Taylor", "Harper Moore", "Anthony White", "Evelyn Martin",
    "David Jackson", "Abigail Thompson", "Joseph Lee", "Elizabeth Harris",
    "Benjamin Clark", "Chloe Lewis", "Andrew Walker", "Ella Hall",
    "Samuel Allen", "Scarlett Young", "Robert King", "Grace Wright",
    "Nicholas Scott", "Lily Green", "Ryan Adams", "Zoe Turner",
    "Lucas Torres", "Aria Carter", "Jack Phillips", "Layla Nelson",
    "Nathan Mitchell", "Avery Roberts", "Dylan Campbell", "Madison Hill",
    "Joshua Rodriguez", "Taylor Simmons", "Luke Baker", "Addison Green",
    "Mason Reed", "Riley Collins", "Liam Bailey", "Emma Bell",
    "Noah Murphy", "Sofia Howard", "Logan Cooper", "Camila Ward",
    "Aaron Peterson", "Luna Gray", "Henry Brooks", "Zoe Bennett",
    "Lucas Patterson", "Ella Rivera", "Samuel Ross", "Layla Henderson",
    "Owen Cook", "Zoey Richardson", "Jackson Foster", "Ariana Bryant",
    "Wyatt Hughes", "Lillian Alexander", "Dylan Washington", "Madison Jordan",
    "Daniel Gibson", "Eva Daniels", "Christopher Graham", "Elizabeth Kelley",
    "Andrew Butler", "Sophia Fisher", "Joseph Stevens", "Harper Wallace",
    "Elijah Woods", "Gabriella West", "Christian Webb", "Isabelle Hayes",
    "Benjamin Ramos", "Avery Price", "William Sanders", "Olivia Ray",
    "Matthew Dunn", "Natalie Brooks", "James Barnes", "Aria Coleman",
    "John Perry", "Lily Ellis", "Nicholas Vasquez", "Scarlett Schneider",
    "Anthony Ortiz", "Chloe Ruiz", "Ethan Wagner", "Sophia Lynch",
    "Michael James", "Mia Santiago", "Lucas Hudson", "Ava Kelley",
    "Samuel Ford", "Emma Harmon", "Henry Weaver", "Isabelle Bishop",
    "Elijah Gardner", "Chloe Stanley", "Dylan Fields", "Zoe Nichols",
    "Wyatt Hart", "Sophia Holland", "Joseph Riley", "Aria Murray",
    "William Matthews", "Emily Fleming", "Ryan Rhodes", "Abigail Aguilar",
    "Robert Summers", "Olivia Drake", "Benjamin Wade", "Chloe Peters",
    "John Soto", "Sophia Doyle", "Ryan Garner", "Ava Schultz",
    "Daniel Moss", "Ella Hoover", "James Cline", "Natalie Perkins",
    "Aaron", "Bella", "Connor", "Daisy", "Elijah", "Fiona",
    "Grant", "Holly", "Ian", "Jade", "Kyle", "Lila",
    "Mason", "Nora", "Oscar", "Paige", "Quentin", "Rosa",
    "Sean", "Tara", "Ulysses", "Vera", "Walter", "Xena",
    "Yusuf", "Zara", "Brent", "Cecilia", "Dexter", "Ella",
    "Felix", "Gwen", "Hugo", "Ivy", "Jesse", "Kendra",
    "Leo", "Mila", "Nate", "Opal", "Preston", "Quinn",
    "Riley", "Stella", "Troy", "Uma", "Victor", "Whitney",
    "Xander", "Yasmine", "Zane", "Blair", "Carter", "Delia",
    "Ezra", "Frances", "Greg", "Helena", "Isaac", "Joanna",
    "Keith", "Luna", "Martin", "Nina", "Otis", "Penelope",
    "Ray", "Sierra", "Timothy", "Ursula", "Vincent", "Wanda",
    "Xavier", "Yara", "Zack", "Beatrice", "Clint", "Dana",
    "Eric", "Felicia", "Gerald", "Heidi", "Iris", "Justin",
    "Kelly", "Lloyd", "Monica", "Nelson", "Olga", "Peter",
    "Rita", "Saul", "Trina", "Upton", "Violet", "Wayne",
    "Xiomara", "Yvonne", "Zelda", "Bernard", "Cheryl", "Dwight",
    "Eve", "Francis", "Glenda", "Horace", "Ingrid", "Jerome",
    "Kristen", "Lance", "Meredith", "Nigel", "Odette", "Phoebe",
    "Roland", "Sylvia", "Trent", "Ursuline", "Vance", "Wilma",
    "Xerxes", "Yvette", "Zeke",
    "blueastral42", "binarysky", "lunarwave77", "deltavision10",
    "frosteagle", "cosmicfury", "galacticmason9", "helixdream",
    "irisnexus8", "jadehorizon", "nebularkite99", "stellarlynx",
    "mysticzara", "neonivy3", "oceanoscar", "plasmaruby",
    "quantumtroy0", "rubydelta", "solarsteve5", "twilightzane",
    "ultranora4", "vividkyle", "wavelengthlila", "zenxander6",
    "yonderblue", "zephyrwave", "arcaneleo", "silversean7",
    "nebulacara", "driftmila", "eeriejacob2", "falconluna",
    "goldenjade", "horizonalex9", "indigocara", "jungleezra",
    "kinglyamber", "luminalia5", "magentaivy", "northzara11",
    "orbitoliver", "prismruby13", "quantumella", "riversky",
    "solarmiles8", "twinkletara", "ultranate", "violetzoe3",
    "wildxavier", "xeniallucas", "yellowleaf9", "zenithlila",
    "azureezra", "breezekyle15", "clearcloud", "deepdawn",
    "emberella6", "forestfalcon", "glacialgem", "hollowhugo",
    "inkediris7", "jazzedjade", "knighthawk", "lucidleo3",
    "midnightmason", "nobleivy", "outlandoscar10", "polarpeter",
    "questedquinn", "redrivers", "solarsurge", "topaztara5",
    "urbanultra", "vividvale", "whitewave8", "xenonzero",
    "yellowyara", "zonedzane",
    "aaron", "bella", "connor", "daisy", "elijah", "fiona",
    "grant", "holly", "ian", "jade", "kyle", "lila",
    "mason", "nora", "oscar", "paige", "quentin", "rosa",
    "sean", "tara", "ulysses", "vera", "walter", "xena",
    "yusuf", "zara", "brent", "cecilia", "dexter", "ella",
    "felix", "gwen", "hugo", "ivy", "jesse", "kendra",
    "leo", "mila", "nate", "olga", "preston", "quinn",
    "riley", "stella", "troy", "uma", "victor", "whitney",
    "xander", "yasmine", "zane", "blair", "carter", "delia",
    "eric", "frances", "greg", "helena", "isaac", "joanna",
    "keith", "luna", "martin", "nina", "otis", "penelope",
    "ray", "sierra", "timothy", "ursula", "vincent", "wanda",
    "xavier", "yara", "zack", "beatrice", "clint", "dana",
    "ezra", "francesca", "gerald", "heidi", "iris", "justin",
    "kelly", "lloyd", "monica", "nelson", "odette", "peter",
    "barry sanders", "claire winston", "dominic thorne", "erin molloy",
    "franklin west", "grace dobson", "howard sterns", "isabelle truant",
    "jeremy fitch", "karen blake", "lawrence timms", "maureen faulkner",
    "neil cortez", "ophelia wells", "patrick olsen", "quincy adler",
    "rachel harmon", "stuart brink", "tracy mendel", "ulric forbes",
    "valerie sparks", "wayne braddock", "xenia pierce", "yves nicholson",
    "zelda marshall", "adam peters", "brittany cobb", "colleen holt",
    "drew atkins", "estelle royce", "freddie pearce", "gloria chung",
    "harrison blackwood", "irene summers", "jude vargas", "kimberly yates",
    "leroy tillman", "marianne hawthorn", "nick brooks", "olive greene",
    "pauline bassett", "quinton farrow", "rebecca snider", "sheldon cox",
    "tamara dunne", "ulysses gold", "vivian lockett", "warren morales",
    "xandra goff", "yolanda briggs", "zane fitzpatrick", "alma curtis",
    "bradford burnett", "cassandra neal", "dale pruitt", "elise rothman",
    "forrest blum", "georgette pike", "horatio lambert", "ivana sheridan",
    "jethro harding", "katrina poole", "luther benson", "mavis garrett",
    "nolan christie", "odessa hartman", "preston marino", "quiana holmes",
    "rufus goldstein", "serena bishop", "thaddeus sawyer", "ursula keegan",
    "vernon heath", "wilma bradshaw", "xerxes winn", "yasmine ford",
    "zephyr tate", "antonia langley", "blake edwards", "charlene bailey",
    "derrick swanson",
    "lizloves", "jamesjungle", "nyckid5", "lazyluke", "jkatz7",
    "butterfly", "repeatrepeat", "samuelsam", "lenalane", "dandydan",
    "nanana", "past-liz", "JohnDoe", "rexrocks", "marthamtn",
    "calikid9", "rideride", "tombomb6", "dragonfly", "bobbobbob",
    "tinaturn", "mikemaze", "coolcool", "future-luke", "AlPacino",
    "sallysea", "peterpark5", "hophop", "lanalux4", "queenbee",
    "annann", "kevinkeen", "leolion", "vivivivi", "past-mike",
    "JaneSmith", "nancynotes", "stevenstar3", "wakawaka", "lukelight7",
    "jivejive", "claraclear", "rickrock", "bambambam", "sarasun",
    "frankfrost", "dodododo", "future-jane", "LucasLucky", "paulplays",
    "quincyquest2", "ronron", "sonnyshine5", "tacotaco", "vivaviva",
    "waltwonder", "xeroxerox", "yayayaya", "zazazaza", "past-lana",
    "BobBuilder", "tedtalks", "ursulaunder4", "vanvan", "willawind6",
    "xyloxylo", "yoyo-yo", "zackzone", "aaronaero", "bebebebe",
    "cecec", "dededed", "ellaelegant", "fifififi", "greggreat",
    "hannahhill", "future-fiona", "true-fake-fred", "DoraDream"
)
